name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 🔥 MUST COME BEFORE KUBECTL
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Image
        run: echo "IMAGE=ghcr.io/ajinkm/eks-cicd-github-actions-terraform:${{ github.sha }}" >> $GITHUB_ENV

      - name: Update Manifest
        run: bash scripts/update-manifest.sh $IMAGE

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy
        run: kubectl apply -f k8s/deploy.yaml
