name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Tag
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: docker build -t ghcr.io/${{ github.repository }}:$TAG .

      - name: Push Image
        run: docker push ghcr.io/${{ github.repository }}:$TAG
